<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_deleteSelected</name>
   <tag></tag>
   <elementGuidId>b537e551-4536-43f6-a4fa-d1cd671e34ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_btnDelete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_btnDelete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb8cf0be-4427-4ea1-b456-7618d98bfe37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>52f2b035-b24d-472b-bc23-1cdf0f48af07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$btnDelete</value>
      <webElementGuid>a0796501-8fba-42ee-9ff7-815651cee0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Delete Selected</value>
      <webElementGuid>042dd421-1098-4cd9-bac7-dd8b45e48934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_btnDelete</value>
      <webElementGuid>908b153c-984d-4ab9-a506-7120993e0cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnDeleteSelected</value>
      <webElementGuid>8f15f124-8869-4d30-a6f7-b3cfe10b5c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_btnDelete&quot;)</value>
      <webElementGuid>473e3bfa-9bff-4ce8-96aa-e978e2bccda5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_btnDelete']</value>
      <webElementGuid>0a4dedbb-8af8-4a60-8db1-eeb8d346114a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/table/tbody/tr/td[2]/div[2]/input</value>
      <webElementGuid>0435d82f-f7fe-49f4-936c-aac679037150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div[2]/input</value>
      <webElementGuid>276b0df3-fa90-400c-a4af-6b015c6edfb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$MainContent$btnDelete' and @id = 'ctl00_MainContent_btnDelete']</value>
      <webElementGuid>b89d3e91-964b-4358-ac29-c98a90d894d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
