<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_ourOrder</name>
   <tag></tag>
   <elementGuidId>690a9f33-2c54-48a3-98b0-0587df41877f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_orderGrid_ctl02_OrderSelector']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_orderGrid_ctl02_OrderSelector</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a2b28bc-d049-4ac9-b5d1-d78020738834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_orderGrid_ctl02_OrderSelector</value>
      <webElementGuid>1e3e3c4b-3e6f-4e3d-9b49-771cb0285a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5018948a-e611-4340-9c36-2056b739738f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$orderGrid$ctl02$OrderSelector</value>
      <webElementGuid>42eb6ae3-dd2e-4b40-a14d-58089331c343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_orderGrid_ctl02_OrderSelector&quot;)</value>
      <webElementGuid>d60982aa-6996-410c-bc98-773bb33d3bf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_orderGrid_ctl02_OrderSelector']</value>
      <webElementGuid>0658147a-ea4d-4505-aa81-ac212e7d6c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_orderGrid']/tbody/tr[2]/td/input</value>
      <webElementGuid>2071e04e-21eb-4a34-b1a4-13949c011a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>20e232fd-7874-4caa-b7a9-e0f62c0d058a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_MainContent_orderGrid_ctl02_OrderSelector' and @type = 'checkbox' and @name = 'ctl00$MainContent$orderGrid$ctl02$OrderSelector']</value>
      <webElementGuid>a82eac29-3925-48ac-853a-80900eea402f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
