<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>imagebutton_edit</name>
   <tag></tag>
   <elementGuidId>cc44925d-4d6d-44c1-bf05-90ba3bdad8f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='image']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;image&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf8552ec-0193-4d1e-999c-cc7b7e376558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>ec5aa504-aa1a-4a8a-89e7-cee84b1a8f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>App_Themes/Default/images/button_edit.gif</value>
      <webElementGuid>f4b5f03b-d309-4079-b9ef-ec18478bc578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>ff99d2ba-8272-4b53-a0e0-c6ad3cf37b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$MainContent$orderGrid','editOrder$0')</value>
      <webElementGuid>676b77ac-b55f-4d98-8be8-d0e82c3d9be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_orderGrid&quot;)/tbody[1]/tr[2]/td[13]/input[1]</value>
      <webElementGuid>f4909c11-ace0-4501-955a-5c1f327de3c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='image']</value>
      <webElementGuid>ff787383-a2f8-45cc-978c-2048337111fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_orderGrid']/tbody/tr[2]/td[13]/input</value>
      <webElementGuid>b1597acf-febf-4c69-9f4a-2eb3d1c38892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[13]/input</value>
      <webElementGuid>090d2c08-0905-42c6-80d1-6c61838fa210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @src = 'App_Themes/Default/images/button_edit.gif' and @alt = 'Edit']</value>
      <webElementGuid>3d0cfceb-728f-4b51-bd3b-ef2b2f0c92eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
