<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>output_cardNumber</name>
   <tag></tag>
   <elementGuidId>07ddc2b0-5944-402c-b237-0d384ea6892b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_MainContent_orderGrid']/tbody/tr[2]/td[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>20207a93-0695-4b4c-90bd-58081e61cd9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5645897821328256</value>
      <webElementGuid>243fb27b-f771-4017-ba6b-a3c00590b577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_orderGrid&quot;)/tbody[1]/tr[2]/td[11]</value>
      <webElementGuid>7be0b772-aee2-4215-8318-1631d685b05b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_orderGrid']/tbody/tr[2]/td[11]</value>
      <webElementGuid>9c94eee0-940c-486e-82a2-ca22560aa523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MasterCard'])[1]/following::td[1]</value>
      <webElementGuid>836b9805-15c1-4f3d-8885-a07dcb20ede4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tamilnadu'])[1]/following::td[3]</value>
      <webElementGuid>d0656e9f-9fa0-4013-b149-ef8fba1dfc2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paul Brown'])[1]/preceding::td[4]</value>
      <webElementGuid>38137bea-56f1-41ff-bf25-f8fbe774792f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ScreenSaver'])[1]/preceding::td[5]</value>
      <webElementGuid>f1b068a9-def5-41e3-946e-c5bd2389099a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5645897821328256']/parent::*</value>
      <webElementGuid>3eac12d4-2c65-4ae6-935e-8dcc071d5db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]</value>
      <webElementGuid>8e6e451d-d81b-4fec-8222-aa55a2766d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '5645897821328256' or . = '5645897821328256')]</value>
      <webElementGuid>41a837a1-9ef2-4570-96e8-a5f959787c7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
