<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_reset</name>
   <tag></tag>
   <elementGuidId>2b346758-112e-450b-bb79-0d6df4e3cc81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Reset']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.buttons_process > input.btn_dark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b21ad04-b5f2-4ae2-b45d-71e5b6801694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>reset</value>
      <webElementGuid>0a1ce80a-7a62-48c2-8a8e-1fd938c05eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Reset</value>
      <webElementGuid>5505f4a5-8fa7-4000-a3b6-a197ba35de05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_dark</value>
      <webElementGuid>cb2127ce-cb62-4e4a-9f72-47f0c1bad445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>UpdateFields()</value>
      <webElementGuid>71a9075c-eb91-4469-990d-bab7bdfa0584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_fmwOrder&quot;)/tbody[1]/tr[1]/td[1]/div[@class=&quot;buttons_process&quot;]/input[@class=&quot;btn_dark&quot;]</value>
      <webElementGuid>14248a4d-f0bc-4a2c-a6d7-37bdd79f7395</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Reset']</value>
      <webElementGuid>41170d26-47e3-4106-a8ed-2555064c8658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_fmwOrder']/tbody/tr/td/div/input</value>
      <webElementGuid>bd8426f4-0442-4d3a-b3c7-805a63d5505a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/input</value>
      <webElementGuid>8af1c7f6-e05b-496d-97a9-2ac7533d8ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'reset']</value>
      <webElementGuid>6255c330-fd01-4d40-82f2-5eb73dd310e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
