<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Total</name>
   <tag></tag>
   <elementGuidId>dc900e17-3790-48b6-b0a0-0fdc59443f8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Calculate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn_dark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f5eabc7-22b3-4875-94d7-95b1fc647cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e9057d51-0062-4dbc-901b-64acf2d76799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Calculate</value>
      <webElementGuid>d59287a9-32ad-407f-a2dd-71a8ca5d885b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_dark</value>
      <webElementGuid>8b117d66-fe70-46a1-b567-3d73f6937472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>productsChanged(); return false;</value>
      <webElementGuid>755f63d5-481f-45a7-aac8-53401b0d1211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_fmwOrder&quot;)/tbody[1]/tr[1]/td[1]/ol[1]/li[5]/input[@class=&quot;btn_dark&quot;]</value>
      <webElementGuid>4df47f7b-39c3-4ed4-991d-541323184312</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Calculate']</value>
      <webElementGuid>ad841151-6fbb-40a8-be78-76ef943e0f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_fmwOrder']/tbody/tr/td/ol/li[5]/input[2]</value>
      <webElementGuid>caff13d7-869f-4457-aa22-4f9ae2963400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/input[2]</value>
      <webElementGuid>c08fb2cb-de0d-4c0d-ac9a-6a4922a2e765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>a6e90444-1610-4277-88d0-57be9db9b612</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
