<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__city</name>
   <tag></tag>
   <elementGuidId>64d2aa28-3812-492c-ab3c-5d450ec703a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_fmwOrder_TextBox3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_fmwOrder_TextBox3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>685b2970-34ec-4afe-b711-7ba4e69a2f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$fmwOrder$TextBox3</value>
      <webElementGuid>a692bdd8-4020-4878-b75b-5c7acc31f591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef29efe8-9706-4b2e-8317-0b15db6aaa9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_fmwOrder_TextBox3</value>
      <webElementGuid>b171f1f7-9156-403a-ace9-910d4bcbf996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_fmwOrder_TextBox3&quot;)</value>
      <webElementGuid>64646b40-2b08-496d-a10a-a1d84f2f6ef4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_fmwOrder_TextBox3']</value>
      <webElementGuid>8dd64948-1f5f-4209-8401-98d1f7a13ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_fmwOrder']/tbody/tr/td/ol[2]/li[3]/input</value>
      <webElementGuid>fba8f0d9-57aa-40e7-a47a-aaaf7ca6fa0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol[2]/li[3]/input</value>
      <webElementGuid>466095cb-e2b1-4ec1-bb0d-5d6fea543162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$MainContent$fmwOrder$TextBox3' and @type = 'text' and @id = 'ctl00_MainContent_fmwOrder_TextBox3']</value>
      <webElementGuid>98260b9c-0ea4-4109-8e1a-70026b726984</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
