<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_selectproduct</name>
   <tag></tag>
   <elementGuidId>b019623f-2aed-4145-83b4-41dd962b8f00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ctl00_MainContent_fmwOrder_ddlProduct']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_fmwOrder_ddlProduct</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cadac022-a960-4550-ac0e-266eb612133f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$fmwOrder$ddlProduct</value>
      <webElementGuid>aae87ab9-85fe-4f57-b805-2a042b6e595f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_fmwOrder_ddlProduct</value>
      <webElementGuid>12c1c7e9-34b9-422c-9c9c-83c7a1417d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>productsChanged()</value>
      <webElementGuid>0da6a3a5-116a-4265-a85e-67d27ac28bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			MyMoney
			FamilyAlbum
			ScreenSaver

		</value>
      <webElementGuid>a9a628d2-fb2f-4cc5-8cf1-b6b11e3b0786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_fmwOrder_ddlProduct&quot;)</value>
      <webElementGuid>16143381-a5bb-4f82-a6ab-bd08aff122ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ctl00_MainContent_fmwOrder_ddlProduct']</value>
      <webElementGuid>24a9da65-8078-4ede-8ed9-127360d21164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_fmwOrder']/tbody/tr/td/ol/li/select</value>
      <webElementGuid>892d1e34-72d6-4402-aa7c-0d43d4bcf959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>fecc6a9f-c357-4acb-b76e-9e8b443c5cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::select[1]</value>
      <webElementGuid>2dbe5408-6392-4d4a-b5c0-d5e55f6f2c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>29befd36-53d9-469d-a846-10c229d5b581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$MainContent$fmwOrder$ddlProduct' and @id = 'ctl00_MainContent_fmwOrder_ddlProduct' and (text() = '
			MyMoney
			FamilyAlbum
			ScreenSaver

		' or . = '
			MyMoney
			FamilyAlbum
			ScreenSaver

		')]</value>
      <webElementGuid>76302a72-697c-4288-830f-3dd23d8773fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
