<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>output_Discounttext</name>
   <tag></tag>
   <elementGuidId>89dfb177-2aa0-444b-af08-ac5ab9ad9d74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_fmwOrder_txtDiscount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_fmwOrder_txtDiscount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60b9e8e4-eb2e-43fe-b4c7-3942146415ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$fmwOrder$txtDiscount</value>
      <webElementGuid>0baea0e3-8d40-44d1-ba67-eaaec8b69043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f7f61f6-d0d9-4579-83ae-01dba13d2ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_fmwOrder_txtDiscount</value>
      <webElementGuid>1b8f5a5b-a7b5-43d1-8ba0-f78ded57c58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_fmwOrder_txtDiscount&quot;)</value>
      <webElementGuid>13b39568-a659-4458-95a9-3f8cdfc7d32c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_fmwOrder_txtDiscount']</value>
      <webElementGuid>dcb84dd5-b179-4e5f-9924-f163eb294426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_fmwOrder']/tbody/tr/td/ol/li[4]/input</value>
      <webElementGuid>d883593d-6e89-4703-a8e7-6e7bacdd2660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/input</value>
      <webElementGuid>d3acce7d-1717-4380-813e-74061bf20ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$MainContent$fmwOrder$txtDiscount' and @type = 'text' and @id = 'ctl00_MainContent_fmwOrder_txtDiscount']</value>
      <webElementGuid>e62ec3de-7e51-4499-b347-5268b5e4e9dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
