<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>output_Totaltext</name>
   <tag></tag>
   <elementGuidId>5e716978-1936-417b-91fd-c0fe8ee872ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_fmwOrder_txtTotal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_fmwOrder_txtTotal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0adaafe-7ea0-43bb-99a6-f79462a5f89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$fmwOrder$txtTotal</value>
      <webElementGuid>d51a4593-c6a0-440e-af9b-15e32aef503e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e489f937-8491-4bf0-9659-cf84d585dbbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_fmwOrder_txtTotal</value>
      <webElementGuid>625d2e5c-a1d6-4322-9e94-968716a746ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_fmwOrder_txtTotal&quot;)</value>
      <webElementGuid>2775f68d-9dff-434d-9e4d-13657e3c3d5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_fmwOrder_txtTotal']</value>
      <webElementGuid>fba49d64-f5ff-4edf-b630-71062567961c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_fmwOrder']/tbody/tr/td/ol/li[5]/input</value>
      <webElementGuid>cb70f6e3-e631-4455-bf59-42d86d1b2004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/input</value>
      <webElementGuid>39c4b4c8-d700-4d7a-8060-548fd3463ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$MainContent$fmwOrder$txtTotal' and @type = 'text' and @id = 'ctl00_MainContent_fmwOrder_txtTotal']</value>
      <webElementGuid>90d68f80-7ae5-40d2-ada6-11dc5394d2bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
