<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radioButton__MasterCard</name>
   <tag></tag>
   <elementGuidId>59e7cf45-c2de-40c2-a0a2-c55971e9f3d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_fmwOrder_cardList_1']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'ctl00_MainContent_fmwOrder_cardList_1' and @type = 'radio' and @name = 'ctl00$MainContent$fmwOrder$cardList']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_fmwOrder_cardList_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87b2c7ad-f27c-4fdd-820c-665b732d155c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_fmwOrder_cardList_1</value>
      <webElementGuid>03328da5-9a04-42f4-ae59-3ec4333538b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8d27272a-4ee5-44bd-8fa1-8252ea89f702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$fmwOrder$cardList</value>
      <webElementGuid>80a6bc85-769f-47b9-8ad2-ec681db6321a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>MasterCard</value>
      <webElementGuid>47a2f963-c5be-485f-9507-6ccd499a622a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_fmwOrder_cardList_1&quot;)</value>
      <webElementGuid>d7d6c22b-40fe-40b1-afe8-22eac327c870</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_fmwOrder_cardList_1']</value>
      <webElementGuid>93e3c5a8-9ebc-4533-ae26-e116cbee4fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_fmwOrder_cardList']/tbody/tr/td[2]/input</value>
      <webElementGuid>3ef048f2-695d-486b-893a-b259dfabf870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>064ce5cd-3ed6-4f83-bfc5-07c063fda060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_MainContent_fmwOrder_cardList_1' and @type = 'radio' and @name = 'ctl00$MainContent$fmwOrder$cardList']</value>
      <webElementGuid>76120f8f-4434-436b-9a05-4729ab984c4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
