<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radioButton_Americanexpress</name>
   <tag></tag>
   <elementGuidId>79e3bbf9-08d4-4fc2-8514-bf13511029d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_fmwOrder_cardList_2']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ctl00_MainContent_fmwOrder_cardList_2&quot;)[count(. | //*[@id = 'ctl00_MainContent_fmwOrder_cardList_2' and @type = 'radio' and @name = 'ctl00$MainContent$fmwOrder$cardList' and @value = 'American Express']) = count(//*[@id = 'ctl00_MainContent_fmwOrder_cardList_2' and @type = 'radio' and @name = 'ctl00$MainContent$fmwOrder$cardList' and @value = 'American Express'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_fmwOrder_cardList_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a902605-6f95-4f91-99d0-36efabbbe186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_fmwOrder_cardList_2</value>
      <webElementGuid>a5700e93-cdd2-44dd-9d35-5d19e68740a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e5f21a3d-140f-490a-9bcf-55af4f06c555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$fmwOrder$cardList</value>
      <webElementGuid>8975d255-0238-454f-b433-409e589febdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>American Express</value>
      <webElementGuid>7f98a3a9-1ca9-4149-b29d-b8cc78bc034e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_fmwOrder_cardList_2&quot;)</value>
      <webElementGuid>1d4b9da2-d4ba-4fd5-b83f-37967b8da476</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_fmwOrder_cardList_2']</value>
      <webElementGuid>0356487e-cba1-4fa1-8afe-2d36bba9f57e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_fmwOrder_cardList']/tbody/tr/td[3]/input</value>
      <webElementGuid>89d54d7b-93de-4340-b37a-939f18ba43da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>5850b577-c3ab-4746-adc4-175eb7394200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_MainContent_fmwOrder_cardList_2' and @type = 'radio' and @name = 'ctl00$MainContent$fmwOrder$cardList']</value>
      <webElementGuid>c69ff7f0-fffc-4c27-aba8-dc533a08037d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
